title: MY Profile.
author: Muhammadim Yusoff Jamaluddin
email: muhammadimyusoff@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hello and Welcome to MY GitHub Profile, Muhammad Yusoff Github Profile. This is my personal Github Profile for potencial recruit and my road to growth and learning.
  Click on the link for full view of my GitHub Profile. See you there!
  
# You can edit this line in _config.yml. 
# It will appear in your document head meta (for Google search results)
# and in your feed.xml site description.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  github.com/MuhammadimYusoff # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
